version: '3.4'

services:
    arthub.api:
        image: ${DOCKER_REGISTRY-}arthubapi
        build:
            context: .
            dockerfile: ArtHub.API/Dockerfile
    arthubDb:
        container_name: arthubDb
        image: "mcr.microsoft.com/mssql/server:2022-latest"

volumes:
    arthubDb_data: